import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

import { AuthContextProvider } from './context/auth-context';
import dynamic from 'next/dynamic';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Providers = dynamic(() => import("@/app/providers"), { ssr: false });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
